src/main/java/com/devpro/entities/Blog.java
package com.devpro.entities;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Lob;
import javax.persistence.Table;
import java.time.LocalDateTime;

@Entity
@Table(name = "tbl_blog")
@NoArgsConstructor
@AllArgsConstructor
@Getter
@Setter
public class Blog extends BaseEntity{
	
	@Column(name="title", length = 500)
	private String title;
	
	@Column(name="description", length = 500)
	private String description;
	
	
	@Column(name="image", length = 500)
	private String image;
	
	@Lob
	@Column(name = "content", columnDefinition = "LONGTEXT")
	private String content;

}

src/main/java/com/devpro/entities/Contact.java
package com.devpro.entities;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;


@Entity
@Table(name = "tbl_contact")
public class Contact extends BaseEntity {
	
	@Column(name = "name", nullable = false)
	private String name;
	
	@Column(name = "email", nullable = false)
	private String email;
	
	@Column(name = "request_type")
	private String requestType;
	
	@Column(name = "message", nullable = false)
	private String message;

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getRequestType() {
		return requestType;
	}

	public void setRequestType(String requestType) {
		this.requestType = requestType;
	}

	public String getMessage() {
		return message;
	}

	public void setMessage(String message) {
		this.message = message;
	}
	
	
}

src/main/java/com/devpro/model/Contact.java
package com.devpro.model;

public class Contact {
	private String name;
	private String mail;
	private String message;
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getMail() {
		return mail;
	}
	public void setMail(String mail) {
		this.mail = mail;
	}
	public String getMessage() {
		return message;
	}
	public void setMessage(String message) {
		this.message = message;
	}
	
	
}

src/main/java/com/devpro/controller/BaseController.java
package com.devpro.controller;

import java.util.ArrayList;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.ModelAttribute;

import com.devpro.entities.Blog;
import com.devpro.entities.Brand;
import com.devpro.entities.Category;
import com.devpro.entities.Product;
import com.devpro.entities.SaleOrder;
import com.devpro.repositories.BlogRepo;
import com.devpro.repositories.BrandRepo;
import com.devpro.repositories.CategoryRepo;
import com.devpro.repositories.ProductRepo;
import com.devpro.repositories.SaleOrderRepo;
import com.devpro.services.BlogService;
import com.devpro.services.BrandService;
import com.devpro.services.ProductService;

@Controller
public abstract class BaseController {
	
	@Autowired
	CategoryRepo categoryrepo;
	@Autowired
	ProductRepo productRepo;
	@Autowired
	BrandRepo brandRepo;
	@Autowired
	BlogRepo blogRepo;
	@Autowired
	SaleOrderRepo saleOderRepo;
	@Autowired
	ProductService productService;
	@Autowired
	BrandService brandService;
	
	@Autowired
	protected
	BlogService blogService;
	
	@ModelAttribute("orders")
	public List<SaleOrder> getOrders(){
		return saleOderRepo.findAll();
	}
	
	@ModelAttribute("categories")
	public List<Category> getCategories(){
		return categoryrepo.findAll();
	}
	
	@ModelAttribute("products")
	public List<Product> getProduct(){
		return productRepo.findAllByStatus(1);
	}
	
	@ModelAttribute("brands")
	public List<Brand> getBrand(){
		return brandService.getBrands();
	}
	
	@ModelAttribute("pagesss")
	public Integer getAmountPages(final ModelMap model){
		List<Product> list = productRepo.findAll();
		Integer pagess = list.size()/12;
		if(list.size()% 2 != 0) {
			pagess+=1;
		}
		return pagess;
	}
	
	@ModelAttribute("blogs")
	public List<Blog> getBlog(){
		return blogRepo.findAll();
	}
	
}

src/main/java/com/devpro/controller/BlogController.java
package com.devpro.controller;

import com.devpro.entities.Blog;
import com.devpro.repositories.BlogRepo;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;

@Controller
@RequestMapping("/blogs")
public class BlogController extends BaseController{

    @Autowired
    private BlogRepo blogRepo;

    @GetMapping("/detail/{id}")
    public String index(final ModelMap model, @PathVariable Integer id){
        Blog blog = blogRepo.getOne(id);
        model.addAttribute("blog",blog);
        return "front-end/detail-blog";
    }
}

src/main/java/com/devpro/controller/ContactController.java
package com.devpro.controller;


import java.time.LocalDate;
import java.time.LocalDateTime;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import com.devpro.entities.Contact;
import com.devpro.repositories.ContactRepos;
import com.devpro.services.SendEmailService;

@Controller
public class ContactController extends BaseController{

	@Autowired
	ContactRepos contactRepos;
	
	@Autowired
	SendEmailService sendEmailService;
	
	/**
	 * 
	 * @param model:    trung gian trao đổi thông tin giữa Controller và View(Jsp)
	 * @param request:  Chứa các thông tin Trình Duyệt truy vấn thông qua mẫu:
	 *                  ?abc=xyz
	 * @param response: Dữ liệu trả về Trình Duyệt.
	 * @return
	 * @throws Exception
	 */
	@RequestMapping(value = { "/contact" }, method = RequestMethod.GET)
	public String index(final ModelMap model, final HttpServletRequest request, final HttpServletResponse response)
			throws Exception {
		return "front-end/contact";
	}
	
	@PostMapping("/contact")
	public String saveContact(final HttpServletRequest request) {
		Contact con = new Contact();
		con.setName(request.getParameter("name"));
		con.setEmail(request.getParameter("email"));
		con.setMessage(request.getParameter("message"));
		con.setCreatedDate(LocalDate.now());
		contactRepos.save(con);
		
		sendEmailService.sendMail(request.getParameter("email"), "MonaWatch", "Dear "+request.getParameter("name")+",\nChúng tôi đã nhận được tin nhắn của bạn"
				+ "Chúng tôi rất xin lỗi về sự bất tiện này. Chúng tôi cảm ơn bạn và sẽ đưa ra giải pháp về vấn đề của bạn!"
				+ "\nBest guards");
		return "front-end/contact";
	}
	 
}

src/main/webapp/WEB-INF/views/front-end/blog.jsp
<!DOCTYPE html>
<%@ page language="java" contentType="text/html; charset=utf-8" pageEncoding="utf-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib prefix="javatime" uri="http://sargue.net/jsptags/time" %>
<html>
<head>

    <meta charset="utf-8">
    <title>Blogs</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="Themesbrand" name="author">
    <jsp:include page="/WEB-INF/views/front-end/common/css.jsp"/>
</head>
<style>
    .text-outer{
        color: #0b0b0b;
    }
    .title-blog {
        margin-top: 50px;
        margin-left: 15px;
        margin-right: 15px;
        border-bottom: 1px solid #70c248;
    }

    .title-blog span {
        position: relative;
        display: inline-block;
        background: #69be28;
        color: #fff;
        text-transform: uppercase;
        padding: 11px 20px;
        font-size: 20px;
    }

    .title-blog span::after {
        content: "";
        width: 0;
        position: absolute;
        left: 100%;
        top: 0;
        height: 0;
        border-style: solid;
        border-width: 53px 0 0 48px;
        border-color: transparent transparent transparent #70c248;
    }

    .blog-s {
        font-size: 16px;
    }

    .blog-s img {
        height: 100%;
    }

    .blog-s ul {
        list-style-type: none;
        padding-top: 20px;
        border-bottom: 1px solid #ccc;
        align-items: center;
    }

    .blog-s ul:nth-last-child(1) {
        border: none;
    }

    .blog-s a {
        overflow: hidden;
        display: block;
    }

    .blog-s a:hover {
        text-decoration: none;
        color: #f0a152;
    }

    .con-blogs {
        margin-top: 20px;
        border: 1px solid #ccc;
    }
</style>
<body data-sidebar="dark">

<!-- Begin page -->
<div id="layout-wrapper">

    <jsp:include page="/WEB-INF/views/front-end/common/header.jsp"/>

    <div class="bg-black-menu">
        <div class="container">
            <div class="menu">
				<span id="icon-close" class="d-md-none"><i
                        class="fas fa-times"></i></span>
                <ul>
                    <li>
                        <div class="search d-flex d-md-none d-block">
                            <div>
                                <input type="text" placeholder="Tìm kiếm...">
                            </div>
                            <div>
                                <button>
                                    <i class="fas fa-search"></i>
                                </button>
                            </div>
                        </div>
                    </li>
                    <li><a href="${pageContext.request.contextPath}/">Trang Chủ</a></li>
                    <li><a href="${pageContext.request.contextPath}/gioithieu">Giới Thiệu</a></li>
                    <li><a href="${pageContext.request.contextPath}/quanAo">Sản phẩm</a></li>
                    <li class="active"><a href="${pageContext.request.contextPath}/blog">Blogs</a></li>
                    <li><a href="${pageContext.request.contextPath}/contact">Liên Hệ</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="container-fluid blog-s">

    <div class="container">
        <div class="title-blog">
            <span>Blogs</span>
        </div>
        <div class="row">
        </div>
        <div class="col-12 container infor">
            <div class="row mt-2">
                <c:forEach var="blog" items="${blogs}">
                    <div class="filler col-md-4 col-12" data-aos="fade-right">
                        <a href="${pageContext.request.contextPath}/blogs/detail/${blog.id}">
                            <div class="con">
                                <div class="img-content mr-3">
                                    <img src="../file/upload/${blog.image}" height="250px" width="100%">
                                </div>
                            </div>
                            <div class="text-outer">
                                <h5>${blog.title}</h5>
                                <p>${blog.description}</p>
                            </div>
                        </a>
                    </div>
                </c:forEach>
            </div>
        </div>
    </div>
</div>
</div>

<!-- Footer -->
<jsp:include page="/WEB-INF/views/front-end/common/footer.jsp"></jsp:include>
<!-- Footer End-->


<!-- END layout-wrapper -->

<!-- Right bar overlay-->
<div class="rightbar-overlay"></div>

<jsp:include page="/WEB-INF/views/front-end/common/js.jsp"/>

</body>
</html>

src/main/webapp/WEB-INF/views/front-end/contact.jsp
<!DOCTYPE html>
<%@ page language="java" contentType="text/html; charset=utf-8"
	pageEncoding="utf-8"%>
<html>
<head>
	<title>Contact V8</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
	<jsp:include page="/WEB-INF/views/front-end/common/css.jsp"></jsp:include>
	<link rel="stylesheet" type="text/css" href="css/util.css">
	<link rel="stylesheet" type="text/css" href="css/main.css">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
<!--===============================================================================================-->
</head>
<body>

	<jsp:include page="/WEB-INF/views/front-end/common/header.jsp"></jsp:include>
	<div class="bg-black-menu">
	<div class="container">
			<div class="menu">
				<span id="icon-close" class="d-md-none"><i
					class="fas fa-times"></i></span>
				<ul>
					<li>
						<div class="search d-flex d-md-none d-block">
							<div>
								<input type="text" placeholder="Tìm kiếm...">
							</div>
							<div>
								<button>
									<i class="fas fa-search"></i>
								</button>
							</div>
						</div>
					</li>
					<li><a
						href="${pageContext.request.contextPath}/">Trang Chủ</a></li>
					<li><a href="${pageContext.request.contextPath}/gioithieu">Giới Thiệu</a></li>
					<li><a href="${pageContext.request.contextPath}/quanAo">Sản phẩm</a></li>
					<li><a href="${pageContext.request.contextPath}/blog">Blogs</a></li>
					<li class="active"><a href="${pageContext.request.contextPath}/contact">Liên
							Hệ</a></li>
				</ul>
			</div>
		</div>
		</div>
	<div class="container-contact100">
		<div class="contact100-map">
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d391.4726495361806!2d105.84317624908874!3d21.01921843602022!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3135ab8fd7aa82af%3A0x17710cf525f36606!2zQ-G6o25oIFPDoXQgSMOsbmggU-G7sSBIw6AgTuG7mWkgKFBDNDUp!5e0!3m2!1svi!2s!4v1639837508314!5m2!1svi!2s" width="100%" height="100%" style="border:0;" allowfullscreen="true" loading="lazy"></iframe>
		</div>

		<div class="wrap-contact100">
			<form class="contact100-form validate-form" action="${pageContext.request.contextPath}/contact" method="post" >
				<span class="contact100-form-title">
					Liên hệ cửa hàng
				</span>

				<div class="wrap-input100 validate-input" data-validate="Bắt buộc nhập họ tên!">
					<input class="input100" type="text" name="name" id="name" placeholder="Họ và tên">
					<span class="focus-input100-1"></span>
					<span class="focus-input100-2"></span>
				</div>

				<div class="wrap-input100 validate-input" data-validate = "Email chưa hợp lệ! ví dụ: ex@abc.xyz">
					<input class="input100" type="text" name="email" id="email" placeholder="Email">
					<span class="focus-input100-1"></span>
					<span class="focus-input100-2"></span>
				</div>
				<div class="wrap-input100 validate-input" data-validate = "Số điện thoại chưa hợp lệ!">
					<input class="input100" type="text" name="phone" id="phone" placeholder="Số điện thoại">
					<span class="focus-input100-1"></span>
					<span class="focus-input100-2"></span>
				</div>

				<div class="wrap-input100 validate-input" data-validate = "Bắt buộc nhập ghi chú!">
					<textarea class="input100" name="message" id="message" placeholder="Ghi chú"></textarea>
					<span class="focus-input100-1"></span>
					<span class="focus-input100-2"></span>
				</div>

				<div class="contact100-form-checkbox">
					<input class="input-checkbox100" id="ckb1" type="checkbox" name="copy-mail">
					<label class="label-checkbox100" for="ckb1">
						Gửi bản sao tới tôi
					</label>
				</div>

				<div class="container-contact100-form-btn">
					<button class="contact100-form-btn">
						Gửi phản hồi
					</button>
				</div>
			</form>
		</div>
	</div>
	<%-- <div class="container">
		<div class="content-footer m-0">
			<div class="left float-left">
				<h3>Đăng kí nhận thông tin</h3>
			</div>
			<div class="right float-right">
				<form class="form-inline"
					action="${pageContext.request.contextPath}/" method="post">

					<div class="input-group mb-2 mr-sm-2">
						<input type="text" class="form-control" id="emailfield"
							placeholder="Email" />
					</div>
					<button type="submit" class="btn btn-info mb-2">Subcribe</button>
				</form>
			</div>
		</div>
	</div>
	</div> --> --%>
	<jsp:include page="/WEB-INF/views/front-end/common/footer.jsp"></jsp:include>
	<div class="social d-none d-lg-block">
		<a href="https://www.facebook.com/tuananhtb99/"><i
			class="fab fa-facebook-f"></i></a> <a
			href="https://www.facebook.com/tuananhtb99/"><i
			class="fab fa-twitter"></i></a> <a
			href="https://www.instagram.com/tuan_oliver/?hl=vi"><i
			class="fab fa-instagram"></i></a> <a
			href="https://www.facebook.com/tuananhtb99/"><i
			class="fab fa-youtube"></i></a>
	</div>



	<div id="dropDownSelect1"></div>

<!--===============================================================================================-->
	<script src="vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/animsition/js/animsition.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/bootstrap/js/popper.js"></script>
	<script src="vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/select2/select2.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/daterangepicker/moment.min.js"></script>
	<script src="vendor/daterangepicker/daterangepicker.js"></script>
<!--===============================================================================================-->
	<script src="vendor/countdowntime/countdowntime.js"></script>
<!--===============================================================================================-->
	<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAKFWBqlKAGCeS1rMVoaNlwyayu0e0YRes"></script>
<!--===============================================================================================-->
	<script src="../js/main.js"></script>
	<script src="../js/contact.js"></script>
	<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-23581568-13');
</script>

</body>
<jsp:include page="/WEB-INF/views/front-end/common/js.jsp"></jsp:include>
</html>

src/main/webapp/WEB-INF/views/front-end/product-detail.jsp
<!DOCTYPE html>
<%@ page language="java" contentType="text/html; charset=utf-8"
         pageEncoding="utf-8" %>
<!-- SPRING FORM -->
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<!-- JSTL -->
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<html>
<head>

    <meta charset="utf-8">
    <title>Chi tiết sản phẩm</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="Premium Multipurpose Admin & Dashboard Template"
          name="description">
    <meta content="Themesbrand" name="author">
    <jsp:include page="/WEB-INF/views/front-end/common/css.jsp"></jsp:include>
    <jsp:include page="/WEB-INF/views/back-end/common/css.jsp"></jsp:include>
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/lightslider/1.1.6/css/lightslider.css"/>
</head>
<style>
    .page-content {
        padding-top: 20px;
    }

    .product-detai-imgs {
        width: 450px;
    }

    product-detai-imgs ul {
        list-style: none outside none;
        padding-left: 0;
        margin-bottom: 0;
    }

    product-detai-imgs li {
        display: block;
        float: left;
        margin-right: 6px;
        cursor: pointer;
        border: 1px solid #ccc;
    }

    .lslide img {
        border: 1px solid #ccc;
        border-radius: 10%;
    }

    product-detai-imgs img {
        display: block;
        height: auto;
        max-width: 100%;
        margin-right: 5px;
    }

    .lSPager img {
        border: 1px solid #ccc;
        border-radius: 20%;
    }

    .detailss, .des {
        font-size: 16px;
    }

    .price .s {
        font-size: 20px;
    }

    .desss {
        text-align: center;
        font-size: 32px;
        font-weight: bold;
        padding: 50px 0 50px 0;
        color: red;
    }

    .lSSlideOuter .lSPager.lSGallery img {
        height: 100px;
    }
</style>
<body>
<!-- Begin page -->


<!-- ========== Left Sidebar Start ========== -->

<!-- Left Sidebar End -->
<!-- ============================================================== -->
<!-- Start right Content here -->
<!-- ============================================================== -->
<jsp:include page="/WEB-INF/views/front-end/common/header.jsp"></jsp:include>
<div class="bg-black-menu">
    <div class="container">
        <div class="menu">
				<span id="icon-close" class="d-md-none"><i
                        class="fas fa-times"></i></span>
            <ul>
                <li>
                    <div class="search d-flex d-md-none d-block">
                        <div>
                            <input type="text" placeholder="Tìm kiếm...">
                        </div>
                        <div>
                            <button>
                                <i class="fas fa-search"></i>
                            </button>
                        </div>
                    </div>
                </li>
                <li><a href="${pageContext.request.contextPath}/">Trang
                    Chủ</a></li>
                <li><a href="${pageContext.request.contextPath}/gioithieu">Giới
                    Thiệu</a></li>
                <li><a href="${pageContext.request.contextPath}/quanAo">Sản phẩm</a></li>
                <li><a href="${pageContext.request.contextPath}/blog">Blogs</a></li>
                <li><a href="${pageContext.request.contextPath}/contact">Liên
                    Hệ</a></li>
            </ul>
        </div>
    </div>
</div>
<div class="container">
    <c:forEach var="product" items="${products }">
        <div class="title-left mt-5">
            <a href="${pageContext.request.contextPath}/">TRANG CHỦ</a><span
                class="m-3">/</span><a
                href="${pageContext.request.contextPath}/quanAo">Thông tin chi tiết</a>
        </div>
        <div class="clearfix"></div>
        <div class="row">
            <div class="col-xl-6">

                <div class="product-detai-imgs mt-5">

                    <ul class="image-products" id="lightSlider">
                        <c:forEach var="img" items="${product.productImages }">
                            <li data-thumb="../file/upload/${img.title }"><img
                                    src="../file/upload/${img.title }" width="100%" height="450px">
                            </li>
                        </c:forEach>
                    </ul>
                </div>

            </div>

            <div class="col-xl-6">
                <div class="mt-4 mt-xl-3">
                    <h1 class="mt-1 mb-3">${product.title }</h1>

                    <div class="text-muted float-left mr-3 ">
                        <span class="bx bx-star text-warning"></span> <span
                            class="bx bx-star text-warning"></span> <span
                            class="bx bx-star text-warning"></span> <span
                            class="bx bx-star text-warning"></span> <span class="bx bx-star"></span>
                    </div>
                    <c:if test="${product.priceSale != null }">
                        <h6 class="text-success text-uppercase">
                            Đang giảm giá : ${product.percentSale}%
                        </h6>
                    </c:if>
                    <c:if test="${product.priceSale == null}">
                        <h5 class="mb-4 price">
                            Giá : <span class="s text-danger mr-2">${product.price}</span>
                        </h5>
                    </c:if>
                    <c:if test="${product.priceSale != null }">
                        <h5 class="mb-4 price">
                            Giá : <span class="mr-2 s "><del class="">${product.price}</del></span>
                            <b class="text-danger s">${product.priceSale}</b>
                        </h5>
                    </c:if>
                    <p class="des text-muted mb-4">${product.shortDes}</p>
                    <div class="row mb-3 detailss">
                        <div class="col-md-6">
                            <div>
                                <p class="text-muted">
                                    <i class="fas fa-trademark mr-2"></i> Thương hiệu : <a
                                        href="#" class="text-primary">${product.brand.name }</a>
                                </p>
                                <p class="text-muted">
                                    <i class="fab fa-product-hunt mr-2"></i> Chất liệu :
                                        ${product.procedurePro }
                                </p>
                                <p class="text-muted">
                                    <i class="fas fa-handshake mr-2"></i> màu sắc :
                                        ${product.waranty }
                                </p>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div>
                                <p class="text-muted">
                                    <i class="far fa-window-maximize mr-2"></i> Kích cỡ :
                                        ${product.sizeSuf }
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="text-center">
                    <button type="button"
                            class="btn btn-primary waves-effect waves-light mt-2 mr-1"
                            data-target="#exampleModal" data-toggle="modal"
                            onclick="Cart.gioHang(${product.id},1);">
                        <i class="bx bx-cart mr-2"></i> Thêm vào giỏ
                    </button>
                    <div class="modal fade" id="exampleModal" tabindex="-1"
                         role="dialog" aria-labelledby="exampleModalLabel"
                         aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">Thông báo</h5>
                                    <button type="button" class="close" data-dismiss="modal"
                                            aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">Tiếp tục mua hàng?</div>
                                <div class="modal-footer">

                                    <button type="button" class="btn btn-primary"
                                            onclick="location.href='${pageContext.request.contextPath}/quanAo'">Tiếp tục
                                    </button>
                                    <button type="button" class="btn btn-secondary"
                                            onclick="location.href='${pageContext.request.contextPath}/hien-thi-san-pham-trong-gio-hang'"
                                            data-dismiss="modal">Vào giỏ hàng
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <a href="tel:+84386950395"
                       class="btn btn-success waves-effect  mt-2 waves-light">
                        <i class="fas fa-phone-alt"></i>Tư vấn
                    </a>
                </div>
            </div>

        </div>
    </c:forEach>
</div>
<div class="desss">Giới thiệu sản phẩm</div>
<c:forEach var="pro" items="${products }">
    <div class="container">${pro.shortDetails }</div>
</c:forEach>
<jsp:include page="/WEB-INF/views/front-end/common/footer.jsp"></jsp:include>

<!-- END layout-wrapper -->


<!-- Right bar overlay-->
<div class="rightbar-overlay"></div>
<jsp:include page="/WEB-INF/views/front-end/common/js.jsp"></jsp:include>
<jsp:include page="/WEB-INF/views/back-end/common/js.jsp"></jsp:include>
<script type="text/javascript">
    $(document).ready(function () {
        // MDB Lightbox Init
        $(function () {
            $("#mdb-lightbox-ui").load("mdb-addons/mdb-lightbox-ui.html");
        });
    });
</script>
<script
        src="https://cdnjs.cloudflare.com/ajax/libs/lightslider/1.1.6/js/lightslider.min.js"></script>
<script
        src="https://cdnjs.cloudflare.com/ajax/libs/lightslider/1.1.6/js/lightslider.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $("#lightSlider").lightSlider({
            gallery: true,
            item: 1,
            auto: true,
            loop: true,
            slideMargin: 0,
            thumbItem: 5
        });
    });
</script>
</body>
</html>